- work-tracker-examples/pom.xml
- work-tracker-examples/spring-boot-example/pom.xml
This will skip the examples module for deployment to Maven
> Skip examples for deployment

- build/bump_version.sh
> improved bump_version script

- .idea/codeStyles/Project.xml
- .idea/codeStyles/codeStyleConfig.xml
> Add codestyle

- work-tracker-core/src/test/java/com/deere/isg/worktracker/ZombieDetectorTest.java
> Fix zombie tests

- work-tracker-examples/spring-example/pom.xml
> address CVE-2018-7489 issue in Jackson

- work-tracker-core/src/main/java/com/deere/isg/worktracker/FloodSensor.java
- work-tracker-core/src/test/java/com/deere/isg/worktracker/FloodSensorTest.java
- work-tracker-servlet/README.md
metadata test fails as I can't figure out how to write it.
> add type of 429 restriction and retry after as metadata.

- work-tracker-core/src/main/java/com/deere/isg/worktracker/FloodSensor.java
- work-tracker-core/src/test/java/com/deere/isg/worktracker/FloodSensorTest.java
- work-tracker-servlet/README.md
- work-tracker-servlet/src/main/java/com/deere/isg/worktracker/servlet/AbstractHttpWorkFilter.java
- work-tracker-servlet/src/test/java/com/deere/isg/worktracker/servlet/AbstractHttpWorkFilterTest.java
> added post process for workFilter w/maheshgaya

- pom.xml
- work-tracker-core/pom.xml
- work-tracker-core/src/main/java/com/deere/isg/worktracker/FloodSensor.java
- work-tracker-servlet/README.md
- work-tracker-servlet/src/main/java/com/deere/isg/worktracker/servlet/ConnectionLimits.java
- work-tracker-servlet/src/main/java/com/deere/isg/worktracker/servlet/HttpFloodSensor.java
- work-tracker-servlet/src/test/java/com/deere/isg/worktracker/servlet/ConnectionLimitsTest.java
> Flexible limits

- work-tracker-core/src/main/java/com/deere/isg/worktracker/FloodSensor.java
- work-tracker-core/src/test/java/com/deere/isg/worktracker/FloodSensorTest.java
- work-tracker-servlet/README.md
- work-tracker-servlet/src/main/java/com/deere/isg/worktracker/servlet/ConnectionLimits.java
- work-tracker-servlet/src/main/java/com/deere/isg/worktracker/servlet/HttpFloodSensor.java
- work-tracker-servlet/src/test/java/com/deere/isg/worktracker/servlet/ConnectionLimitsTest.java
- work-tracker-servlet/src/test/java/com/deere/isg/worktracker/servlet/HttpFloodSensorTest.java
- work-tracker-spring-boot/README.md
- work-tracker-spring/README.md
> Advanced limit

- work-tracker-core/src/test/java/com/deere/isg/worktracker/FloodSensorTest.java
- work-tracker-examples/spring-example/src/main/webapp/WEB-INF/web.xml
- work-tracker-servlet/src/main/java/com/deere/isg/worktracker/servlet/WorkHttpServlet.java
- work-tracker-servlet/src/main/java/com/deere/isg/worktracker/servlet/WorkSummary.java
- work-tracker-servlet/src/test/java/com/deere/isg/worktracker/servlet/WorkHttpServletTest.java
- work-tracker-spring-boot/src/main/java/com/deere/isg/worktracker/spring/boot/WorkTrackerConfigurer.java
- work-tracker-spring/README.md
- work-tracker-spring/UPGRADING.md
- work-tracker-spring/src/main/java/com/deere/isg/worktracker/spring/AbstractSpringWorkFilter.java
- work-tracker-spring/src/main/java/com/deere/isg/worktracker/spring/ServletEndpointRegistry.java
- work-tracker-spring/src/main/java/com/deere/isg/worktracker/spring/SpringWork.java
- work-tracker-spring/src/main/java/com/deere/isg/worktracker/spring/SpringWorkHttpServlet.java
- work-tracker-spring/src/test/java/com/deere/isg/worktracker/spring/AbstractSpringWorkFilterTest.java
- work-tracker-spring/src/test/java/com/deere/isg/worktracker/spring/ServletEndpointRegistryTest.java
- work-tracker-spring/src/test/java/com/deere/isg/worktracker/spring/SpringWorkPostAuthFilterTest.java
- work-tracker-spring/src/test/java/com/deere/isg/worktracker/spring/SpringWorkTest.java
- work-tracker-spring/src/test/java/com/deere/isg/worktracker/spring/TestServletContext.java
Changes in this pr:
- Allow customization of WorkSummaryServlet. Allowing client apps to have endpoints instead of service for outstanding page. SpringWorkSummaryServlet provides an implementation for that.
- Delay endpoint setup for requests that go through Spring lifecycle
- Setup endpoint immediately for Servlets (this will be first step for fixing #14)
- Added logStart for Servlet fixes #14
> Delay endpoint setup for Spring

- work-tracker-spring/src/main/java/com/deere/isg/worktracker/spring/PathMetadataCleanser.java
- work-tracker-spring/src/test/java/com/deere/isg/worktracker/spring/PathMetadataCleanserTest.java
> Handle special characters in path values

- work-tracker-spring/src/main/java/com/deere/isg/worktracker/spring/SpringWork.java
- work-tracker-spring/src/test/java/com/deere/isg/worktracker/spring/SpringWorkTest.java
> Handle special characters in path values #2

- work-tracker-spring/src/main/java/com/deere/isg/worktracker/spring/SpringWork.java
- work-tracker-spring/src/test/java/com/deere/isg/worktracker/spring/SpringWorkTest.java
> fix npe for Pattern.quote for regex

- work-tracker-core/src/main/java/com/deere/isg/worktracker/Work.java
- work-tracker-core/src/test/java/com/deere/isg/worktracker/WorkTest.java
- work-tracker-spring/src/main/java/com/deere/isg/worktracker/spring/SpringWork.java
> allow MDC key validation override by apps

- work-tracker-spring/src/main/java/com/deere/isg/worktracker/spring/AbstractSpringWorkFilter.java
- work-tracker-spring/src/main/java/com/deere/isg/worktracker/spring/ServletEndpointRegistry.java
- work-tracker-spring/src/main/java/com/deere/isg/worktracker/spring/SpringWork.java
- work-tracker-spring/src/test/java/com/deere/isg/worktracker/spring/AbstractSpringWorkFilterTest.java
- work-tracker-spring/src/test/java/com/deere/isg/worktracker/spring/ServletEndpointRegistryTest.java
- work-tracker-spring/src/test/java/com/deere/isg/worktracker/spring/SpringWorkTest.java
This avoids the need to have to check for ContextPath where it applies.
> Change to servletPath instead of URI

- work-tracker-spring/src/main/java/com/deere/isg/worktracker/spring/SpringWorkHttpServlet.java
- work-tracker-spring/src/test/java/com/deere/isg/worktracker/spring/SpringWorkHttpServletTest.java
> make endpoint empty string if null

- work-tracker-core/src/main/java/com/deere/isg/worktracker/FloodSensor.java
- work-tracker-core/src/test/java/com/deere/isg/worktracker/FloodSensorTest.java
- work-tracker-spring/src/test/java/com/deere/isg/worktracker/spring/SpringWorkHttpServletTest.java
> added a max retryAfterSeconds for 5 minutes

- work-tracker-servlet/src/main/java/com/deere/isg/worktracker/servlet/WorkSummary.java
- work-tracker-servlet/src/test/java/com/deere/isg/worktracker/servlet/WorkSummaryTest.java
> break accept header with spaces

- work-tracker-servlet/src/main/java/com/deere/isg/worktracker/servlet/WorkHttpServlet.java
Improve readability for the table
> rm center align for contents in table

- .github/PULL_REQUEST_TEMPLATE.md
* Misspelling in the pull request template leading to a 404 for `CONTRIBUTING.md`.
> Fix Contribution Guidelines link

- work-tracker-spring-boot/README.md
* excludePathPatterns is a function on WorkTrackerConfigurer, but there is no documentation for it. Adding this in to allow consumer to block out noise (i.e. frequent health pings)
> Add documentation for excludePathPatterns

- .travis.yml
- README.md
- pom.xml
- work-tracker-core/src/main/java9/com/deere/isg/worktracker/PlaceHolder.java
- work-tracker-core/src/main/java9/module-info.java
- work-tracker-servlet/README.md
- work-tracker-servlet/src/main/java9/com/deere/isg/worktracker/servlet/PlaceHolder.java
- work-tracker-servlet/src/main/java9/module-info.java
- work-tracker-spring-boot/README.md
- work-tracker-spring-boot/src/main/java9/com/deere/isg/worktracker/spring/boot/PlaceHolder.java
- work-tracker-spring-boot/src/main/java9/module-info.java
- work-tracker-spring/README.md
- work-tracker-spring/src/main/java9/com/deere/isg/worktracker/spring/PlaceHolder.java
- work-tracker-spring/src/main/java9/module-info.java
>  Add module structure support for java 9+

- work-tracker-core/src/main/java9/module-info.java
- work-tracker-servlet/src/main/java9/module-info.java
- work-tracker-spring-boot/pom.xml
- work-tracker-spring-boot/src/main/java9/module-info.java
- work-tracker-spring/src/main/java9/module-info.java
IntelliJ found some additional modules that need required when setting
the language level to 9.
> Add missing module system requires

- work-tracker-core/src/main/java/com/deere/isg/worktracker/StringUtils.java
- work-tracker-core/src/test/java/com/deere/isg/worktracker/StringUtilsTest.java
> Allow _ in ALL_UPPERCASE so that it converts to snake case properly.

- work-tracker-servlet/README.md
- work-tracker-servlet/pom.xml
- work-tracker-servlet/src/main/java/com/deere/isg/worktracker/servlet/HttpWork.java
- work-tracker-servlet/src/main/java/com/deere/isg/worktracker/servlet/HttpWorkPostAuthFilter.java
- work-tracker-servlet/src/main/java9/module-info.java
- work-tracker-servlet/src/test/java/com/deere/isg/worktracker/servlet/HttpWorkPostAuthFilterTest.java
- work-tracker-spring/README.md
- work-tracker-spring/src/main/java/com/deere/isg/worktracker/spring/SpringWork.java
- work-tracker-spring/src/main/java/com/deere/isg/worktracker/spring/SpringWorkPostAuthFilter.java
Some non-Spring applications need this functionality.
> Move the post authentication filter down to the servlet package.

- README.md
- doc/ZOMBIES.md
- work-tracker-spring-boot/README.md
> Document the Zombie Detection feature set.
